services:
  - type: web
    name: calculator
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn --chdir /opt/render/project/src/pricecalc --pythonpath /opt/render/project/src pricecalc.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: STATIC_ROOT
        value: /opt/render/project/src/staticfiles
      - key: STATIC_URL
        value: /static/
      - key: PYTHON_PATH
        value: /opt/render/project/src
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4 