services:
  - type: web
    name: calculator
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd pricecalc && PYTHONPATH=/opt/render/project/src python manage.py runserver 0.0.0.0:10000
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: True
      - key: STATIC_ROOT
        value: /opt/render/project/src/staticfiles
      - key: STATIC_URL
        value: /static/
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DJANGO_SETTINGS_MODULE
        value: pricecalc.settings
      - key: PYTHON_VERSION
        value: 3.11.0 